server:
  port: 7002

#Eureka配置
eureka:
  instance:
    hostname: localhost  #eureka7002.com    #Eureka服务端的实例名称
  client:
    register-with-eureka: false     #是否向Eureka注册中心注册自己，所以为false
    fetch-registry: false    #如果为false，则自己为注册中心
    service-url:       #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群配置：  defaultZone: http://eureka7001.com:7002/eureka/,http://eureka7003.com:7003/eureka/
